export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const SET_INGREDIENTS = 'SET_INGREDIENTS'

export const PARCHASE_BERGER_SUCCESS = 'PARCHASE_BERGER_SUCCESS'
export const PARCHASE_BERGER_FAIL = 'PARCHASE_BERGER_FAIL'
export const ORDER_PARCHESED = 'PARCHASE_BERGER_FAIL'

export const FETCH_ORDERS_START= 'FETCH_ORDERS_START'
export const FETCH_ORDERS_SUCCESS= 'FETCH_ORDERS_SUCCESS'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const LOGOUT = 'LOGOUT'
export const CHECK_AUTH_STATUS = 'CHECK_AUTH_STATUS'

